openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /auth/signin:
    post:
      requestBody:
         $ref: '#/components/requestBodies/loginMode'
      responses:
        '200':
          description: OK

components:
  requestBodies:
    loginMode:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            # The properties correspond to individual form fields
            properties:
              email:
                type: string
              password:
                type: string
            
          
