openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
paths:
  /categories:
    get:
      parameters: 
      - in: header
        name: token
        schema:
          type: string
      responses:
        '200':
          description: OK
  /auth/signin:
    post:
      requestBody:
         $ref: '#/components/requestBodies/loginMode'
      responses:
        '200':
          description: OK

components:
  requestBodies:
    loginMode:
      required: true
      content:
        application/json:
          schema:
            type: object
            # The properties correspond to individual form fields
            properties:
              email:
                type: string # mricky.it@gmail.com
              password:
                type: string # rahasia
          
            
          
