openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /auth:
    get:
      responses:
        '200':
          description: OK
          
