@baseUrl = http://localhost:3000
@contentType = application/json
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJuYW1lIjoiUmlja3kiLCJlbWFpbCI6Im1yaWNreS5pdEBnbWFpbC5jb20ifSwiaWF0IjoxNzAxNTMzMDExfQ.cWwPJaKOI3viADqqLsL2eJFvCn0c8a-lxDNef7Pp984"
### GET
{{baseUrl}}

### Login
POST {{baseUrl}}/api/v1/auth/signin 
content-type: application/json
accept: application/json

{
    "email": "mricky.it@gmail.com",
    "password": "rahasia"
}

### Signup
POST {{baseUrl}}/api/v1/auth/signup 
content-type: application/json
accept: application/json

{
    "email": "ricky@gmail.com",
    "password": "rahasia",
    "confirmPassword": "rahasia"
}

### Categories
#### Get All Categories
GET {{baseUrl}}/api/v1/categories
content-type: application/json
accept: application/json
token: {{token}}

#### Create Category
POST {{baseUrl}}/api/v1/categories
content-type: application/json
accept: application/json
token: {{token}}

{
    "name": "Algoritmas"
}

#### Update Category
PUT {{baseUrl}}/api/v1/categories/11
content-type: application/json
accept: application/json
token: {{token}}

{
    "name": "Algoritmas"
}

#### Delete Category
DELETE {{baseUrl}}/api/v1/categories/11
content-type: application/json
accept: application/json
token: {{token}}


### Books
#### Get All Books
GET {{baseUrl}}/api/v1/books
content-type: application/json
accept: application/json
token: {{token}}
